### ISSUE TITLE
layout-of-source-files.rst 번역

### ISSUE THREAD

**Issue by wooqii** [solidity-korea/solidity-docs-kr#17]
> If the issue you want to register is a `translate` issue, register the issue according to the template below.

### :clipboard: Section
- layout-of-source-files
- layout-of-source-files.rst

### :date: Due Date
- (18.04.20)

**Comment by Hyuntae-91** [comment]
마감기한이 끝난 관계로 이슈 닫도록 하겠습니다. 혹시라도 다시 진행하시려고 하실 경우, 다시 이슈를 열어 주세요. 감사합니다.
