### ISSUE TITLE
assign 형식의 분업 제안

### ISSUE THREAD

**Issue by JaeYeopHan** [solidity-korea/solidity-docs-kr#2]
같은 부분을 동시에 번역하는 상황이 발생할 수 있을 것 같아서, 제안드립니다.
번역에 들어가기 전, 이슈로 등록해두고 해당 이슈를 assign 한 후 시작하여 PR을 올리는 방식은 어떨까요?
해당 이슈는 PR이 merge 된 후, close 하는 Flow로 진행하면 효율적이지 않을까 제안해봅니다 :)

아니면 더 좋은 방안이 있을까요?

**Comment by Kcrong** [comment]
파트를 미리 나눠놓아도 좋을 것 같습니다.

**Comment by gnujoow** [comment]
좋은 생각입니다. :)
다만 issue assign할 때 due date를 같이 올리는것도 좋을것 같아요
예전에 번역프로젝트 진행할 때 assign해놓고 번역하지 않는 경우도 있었거든요 :sad:

**Comment by JaeYeopHan** [comment]
@gnujoow  **due date** 좋은 방법인 것 같습니다 :)

현재 두 가지 안이 나왔는데요,

1. 파트를 미리 나누어서 진행하기
2. 번역을 하고자 하는 부분에 대해 이슈를 올려 진행 (due datae와 함께)

결정만 하면 될 것 같습니다.

제 개인적인 생각으로는 너무 큰 덩어리를 처음에 할당하고 마저 못하는 경우가 발생할 수 있지 않을까? 하는 생각이 들어서 2번으로 진행하면 어떨까 합니다! 다른 분들 의견은 어떠신가요? comment로 달아주세요~ 취합하여 결정합시다!ㅎㅎ

**Comment by gnujoow** [comment]
@JaeYeopHan 

2번으로 가즈아ㅏㅏ

**Comment by dongsam** [comment]
저도 2번이 좋을 것 같습니다!

**Comment by JaeYeopHan** [comment]
2번 안으로 진행하면 될 것 같습니다 :) 해당하는 `ISSUE_TEMPLATE`을 만들어두면 좋을 것 같은데요,

- Section (번역 예정인 docs 부분)
  - with `.rst` file name ? (docs 상 section name과 그에 해당하는 file name을 적는 건 어떨까요?)
- due date

assign은 자기가 자신한테 assign하면 되고, 이 두 가지 말고 더 필요한 건 없어보이는데ㅎㅎ 어떠신가요?

**Comment by gnujoow** [comment]
@JaeYeopHan 좋아요 👍

**Comment by JaeYeopHan** [comment]
`ISSUE_TEMPLATE`까지 등록되었으니 해당 이슈는 close 합니다 :)

**Comment by gnujoow** [comment]
@JaeYeopHan 혹시 Wiki에 contribution 문서에 해당 내용을 추가해주실 수 있나요?

**Comment by JaeYeopHan** [comment]
@gnujoow 추가해주셨네요! :)
