### ISSUE TITLE
contracts.rst 부분 번역

### ISSUE THREAD

**Issue by Ranicorn** [solidity-korea/solidity-docs-kr#29]
> If the issue you want to register is a `translate` issue, register the issue according to the template below.

### :clipboard: Section
- Contracts -> Creating Contracts
- contracts.rst

### :date: Due Date
- (18.12.10)

#### :speech_balloon: et cetera
- contracts.rst 부분이 번역이 안되어 있는 것 같아서 Creating Contracts 부터 번역해보려고 합니다. 기간은 넉넉하게 잡았습니다.

**Comment by Hyuntae-91** [comment]
@Ranicorn 
안녕하세요. 문서 버전 업데이트를 진행할 예정입니다. 혹시라도 본 코멘트를 보신다면, 상위 버전의 문서를 번역 진행해 주시면 감사하겠습니다. 이미 진행된 번역도 한번 더 검수해 주시면 감사하겠습니다. 상위 버전의 문서는 "[이 링크](https://github.com/Hyuntae-91/solidity/tree/develop/docs)" 를 통해 확인 하실 수 있습니다.

**Comment by Ranicorn** [comment]
넵 알겠습니다!

2018년 12월 7일 (금) 오전 9:15, Hyuntae Kim <notifications@github.com>님이 작성:

**Comment by Yunbin-Chang** [comment]
혹시 번역 진행 안하셨다면 이부분 제가 번역해도 될까요?

**Comment by devFallingstar** [comment]
@Ranicorn 
안녕하세요, 번역이 완료되었다면 PR 요청 후, 수락 확인한 뒤 issue close해주시길 바라며, @Yunbin-Chang 님과의 업무 분담에 대하여 논의되었을 경우 해당 내용 현재 issue 로 트래킹 해주시기 바랍니다!

**Comment by Hyuntae-91** [comment]
@Ranicorn 
안녕하세요. 진행상황 업데이트 부탁드립니다.
답변이 없으시면 2019.01.12에 본 issue는 close됩니다.
