### ISSUE TITLE
slack 개설 제안

### ISSUE THREAD

**Issue by gnujoow** [solidity-korea/solidity-docs-kr#3]
번역 이후에 커뮤니티 활성을 위해 슬랙이 있었으면 좋겠습니다.

@dongsam

**Comment by dongsam** [comment]
좋은 생각이십니다! 오늘 중으로 슬랙 생성하여 공유드리겠습니다 :)

**Comment by dongsam** [comment]
https://join.slack.com/t/solidity-korea/shared_invite/enQtMzI5MjE1Njk0NzI3LWNkOWY2ZmJlOGJiYzI1OWYwOTA5Y2VmNzI4ZDhlMDU2OTUwM2Q0ZWExNTg0MWYyNzYxZGI2Yjc1MmNhNTRjMjY

링크를 통해 임시적으로 초대 및 가입 가능하십니다. 
조만간 번역 프로젝트 소개 및 멤버 모집 포스팅과 함께 홍보진행할 예정입니다 !
