### ISSUE TITLE
structure-of-a-contract.rst, contributing.rst 번역

### ISSUE THREAD

**Issue by GHHM** [solidity-korea/solidity-docs-kr#30]
> If the issue you want to register is a `translate` issue, register the issue according to the template below.

### :clipboard: Section
- (Docs section) Contributing
- (File name) contributing.rst

### :date: Due Date
- (18.12.14)

#### :speech_balloon: et cetera
- [ggs134님의 번역](https://ggs134.gitbooks.io/solidityguide/content/42-%EC%BD%98%ED%8A%B8%EB%9E%99%ED%8A%B8%EC%9D%98-%EA%B5%AC%EC%A1%B0.html
) structure-of-a-contract.rst에 옮기겠습니다.
- contributing.rst 번역하겠습니다.

**Comment by Hyuntae-91** [comment]
@GHHM 
안녕하세요. 문서 버전 업데이트를 진행할 예정입니다. 혹시라도 본 코멘트를 보신다면, 상위 버전의 문서를 번역 진행해 주시면 감사하겠습니다. 이미 진행된 번역도 한번 더 검수해 주시면 감사하겠습니다. 상위 버전의 문서는 "[이 링크](https://github.com/Hyuntae-91/solidity/tree/develop/docs)" 를 통해 확인 하실 수 있습니다.

**Comment by devFallingstar** [comment]
안녕하세요, 번역 완료되었다면 PR 요청 뒤, 수락이 확인된 후, issue를 close 해주시기바랍니다 :)

**Comment by Hyuntae-91** [comment]
@GHHM 
안녕하세요. 진행상황 업데이트 부탁드립니다.
답변이 없으시면 2019.01.12에 본 issue는 close됩니다.
