### ISSUE TITLE
bugs.rst 부분 번역

### ISSUE THREAD

**Issue by Hyuntae-91** [solidity-korea/solidity-docs-kr#31]
> If the issue you want to register is a `translate` issue, register the issue according to the template below.

### :clipboard: Section
- bugs
- bugs.rst

### :date: Due Date
- (18.12.06)

#### :speech_balloon: et cetera
버그관련 부분 번역 진행하겠습니다.

**Comment by Hyuntae-91** [comment]
한 문장을 어떻게 번역해야할지 감이 안잡힙니다. 도와 주실 분 계신가요?
다른 문장은 다 번역했는데 다음 문장이 문제네요..

It is also mildly suspicious if a contract was compiled with a version that was not the most recent at the time the contract was created. For contracts created from other contracts, you have to follow the creation chain back to a transaction and use the date of that transaction as creation date.

또한 컨트랙트를 작성한 시점에서 가장 최신 버전이 아닌 컴파일러로 컴파일 되었다면 다소 의심스럽습니다. 다른 컨트랙트들에 의해 만들어진 컨트랙트의 경우, 

you have to follow creation chain back~~~ 부분이 번역이 어렵네요.
코멘트 부탁드립니다.

**Comment by Yunbin-Chang** [comment]
만약 컨트렉트가 작성된 시점에서 가장 최신 버전이 아닌 컴파일러로 컨트렉트가 컴파일 되었다면 다소 의심스럽습니다(suspicious). 다른 컨트렉트들로 부터 만들어진 컨트렉트의 경우, 트렌젝션으로 돌아가 생성 체인을 따르고 그 트렌젝션의 날짜를 생성 날짜로써 사용 해야만 합니다.

> 이렇게 해석하면 되지 않을까 생각해봅니다.
