### ISSUE TITLE
security-considerations.rst 번역

### ISSUE THREAD

**Issue by devFallingstar** [solidity-korea/solidity-docs-kr#34]
> If the issue you want to register is a `translate` issue, register the issue according to the template below.

### :clipboard: Section
- 보안 측면 고려사항 (security-considerations) -> Gas Limit and Loops, Sending and Receiving Ether and Callstack Depth
- security-considerations.rst

### :date: Due Date
- (2018.12.12)

#### :speech_balloon: et cetera
보안 측면 고려사항(security-considerations) 섹션에 있는 Gas Limit and Loops, Sending and Receiving Ether 그리고 Callstack Depth 섹션을 번역하겠습니다.
[원본 문서](https://ggs134.gitbooks.io/solidityguide/content/513-가스-제한-및-루프.html) 확인 해보니, 제목만 번역되어있어, 해당 제목 그대로 사용하도록 하겠습니다.

**Comment by Hyuntae-91** [comment]
@devFallingstar 
안녕하세요. 문서 버전 업데이트를 진행할 예정입니다. 혹시라도 본 코멘트를 보신다면, 상위 버전의 문서를 번역 진행해 주시면 감사하겠습니다. 이미 진행된 번역도 한번 더 검수해 주시면 감사하겠습니다. 상위 버전의 문서는 "[이 링크](https://github.com/Hyuntae-91/solidity/tree/develop/docs)" 를 통해 확인 하실 수 있습니다.

**Comment by devFallingstar** [comment]
@Hyuntae-91 확인하여보니 번역 진행할 부분 뿐 아니라 이전에 번역이 끝난 부분도 변경된 것 같네요. 이슈 다시 오픈하여 0.5.1 버전에 대해서 작성 진행하도록 하겠습니다.
