### ISSUE TITLE
Solidity 문서 버전 업데이트에 관하여

### ISSUE THREAD

**Issue by Hyuntae-91** [solidity-korea/solidity-docs-kr#41]
올해 초에 이미 논의 된 사항으로 보입니다만, 결론이 안난것 같아 다시 올립니다.
논의의 결과는 수작업으로 업데이트를 하는 방식을 채택한것 같습니다.

현재 Solidity 문서버전은 0.5.1로 업데이트 되어있는 상황이고
저희는 0.4.2를 기반으로 번역을 진행하고 있습니다.

먼저 추가된 카테고리를 추가하여 문서 버전을 업그레이드 하고, 추가적으로 진행되었던 번역 문서중 추가내용이 있는지 비교를 하여 수정에 들어가는게 어떤지 제안해 봅니다.
또, 아직 번역이 진행되지 않은 문서가 있다면 업데이트 된 버전으로 수정 후 번역할 것을 제안합니다.

0.5.1 버전에 추가된 카테고리는 다음과 같습니다.
- Resources
- Contract ABI Specification  - "Application Binary Interface Specification" 에서 변경됨 추가내용 있음
- Yul - "Joyfully Universal Language for (Inline) Assembly" 에서 변경됨 내용수정 있음
- LLL
- Keyword Index

이 이슈를 보신 분들은 좋은 의견 부탁드립니다 :)

**Comment by Yunbin-Chang** [comment]
예제를 통한 솔리디티 글에 Micropayment Channel파트가 추가되었습니다. [solidity-by-example.rst]

- 문서양이 매우 많은 정도는 아니니 체크리스트를 만들고 여럿이 단순비교하는 방법도 나쁘지 않을것 같습니다.

**Comment by Hyuntae-91** [comment]
@Yunbin-Chang 좋은 의견 감사합니다 :)
제가 한 부분을 검수 해본 결과, 중간중간 바뀐 부분이 있었습니다.
사소하게 바뀐 부분도 있어서 자세히 보지 않으면 바뀌었을지 모를 부분도 있었으니, 검수시 원문과 비교해 보는게 좋을것 같습니다.

번역이 진행되지 않은 문서는 replacement를 하면 될 것 같고, 더 이상 번역에 참여하지 않는 기여자가 번역한 문서의 경우에는 추가된 부분을 원문으로 작성 한 뒤, 번역을 진행하면 될 것 같습니다.
(물론 짧은 문장의 경우에는 바로 업데이트 하는것도 좋을것 같습니다.)

**Comment by devFallingstar** [comment]
현재 번역이 진행되는 와중에 다시금 문서를 덮어쓰는 것은 오히려 혼란을 야기할 수 있다고 봅니다.

브랜치를 나누어 기존 현재 버전은 아카이브 하고, 0.5.1 번역을 위한 브랜치를 따로 나누는 것은 어떨까요?

**Comment by devFallingstar** [comment]
> 현재 번역이 진행되는 와중에 다시금 문서를 덮어쓰는 것은 오히려 혼란을 야기할 수 있다고 봅니다.
> 
> 브랜치를 나누어 기존 현재 버전은 아카이브 하고, 0.5.1 번역을 위한 브랜치를 따로 나누는 것은 어떨까요?

추가로, 0.5.1 버전 브랜치에 대해서는 두가지 방향이 있다고 생각합니다.

1. 현재 0.4.2 버전의 브랜치를 클론하여 어느정도 한글로 번역된 부분을 유지하며 수정
2. 새로 0.5.1 버전의 브랜치를 오리지널 repo에서 따와서 처음부터 다시 번역

개인적으로 1번 방법을 취하려 하는데, 생각보다 원문 사소한 변화를 체감하기가 어려울 수 있을 것 같아 경계가 필요해보이긴 합니다.
