### ISSUE TITLE
[0.5.1] security-considerations.rst 번역

### ISSUE THREAD

**Issue by devFallingstar** [solidity-korea/solidity-docs-kr#42]
> If the issue you want to register is a `translate` issue, register the issue according to the template below.

### :clipboard: Section
- 보안 측면 고려사항 (security-considerations) -> 첫 부분부터 Callstack Depth까지
- security-considerations.rst

### :date: Due Date
- (2018.12.20) -> (2018.12.25)로 변경

#### :speech_balloon: et cetera
0.5.1 버전 업데이트에 따라 번역 진행 후, 이슈로 과정을 트래킹하고, 문서 업데이트가 어떻게 진행되냐에 따라 PR은 날리지 않도록 하겠습니다.

**Comment by devFallingstar** [comment]
개인 사정으로 일정을 조금 미뤄야할 것 같습니다. Due Date를 12월 25일로 늘리겠습니다.

**Comment by Yunbin-Chang** [comment]
다들 바쁘시네요

**Comment by devFallingstar** [comment]
논문 제출 준비로 인해 진행을 하지 못하였습니다.
죄송합니다만 해당 파일에 대한 번역 진행을 중단하도록 하겠습니다. 

다른 분께서 이어서 해주시면 고맙겠습니다.
