### ISSUE TITLE
문서 업데이트 및 브랜치에 대한 의견

### ISSUE THREAD

**Issue by devFallingstar** [solidity-korea/solidity-docs-kr#43]
이슈 #41 에 작성한 것과 같이 기존 문서를 0.4.2 브랜치로 아카이브하고, 0.5.1 브랜치를 새로 작성하는 것이 어떤가 하는 의견을 남깁니다.

- 현재 버전(0.4.2)를 아카이브하고, 0.5.1 브랜치를 새로 만들어 main 브랜치로 설정

또한, 0.5.1 브랜치를 새로 만들 때, 번역이 하나도 안된 원문 브랜치를 가져와서 시작할지, 함께 어느정도 번역하던 0.4.2 브랜치를 클론하여 시작할지 정해야할 것 같습니다.

두 방식에 따른 장단점이 존재할 것 같은데, 여러분의 의견 부탁드리며, 더 나은 의견이 있다면 말씀해주시기 바랍니다.

**Comment by Hyuntae-91** [comment]
개인적으로 처음부터 시작하는 방법은 굉장한 시간낭비라고 생각합니다. 제가 번역했던 문서는 이미 개인 리포에 0.5.1버전으로 업데이트 해두었는데, 중간중간 바뀐건 있어도 큰 틀은 변화가 없었습니다.

그런 의미에서 말씀하신데로 현재 0.4.2버전은 아카이브하고, 번역하던 0.4.2 브랜치를 클론하는게 좋다고 생각합니다.

**Comment by Hyuntae-91** [comment]
추가 의견을 제시하자면, 0.4.2버전이 0.5.1버전으로 업데이트 되는동안 저희는 0.4.2버전 조차도 다 번역하지 못 했습니다. 기여하는 인원이 많다면 모르겠지만, 현 상황에서 0.5.1을 또 새로 시작한다면, 계속 업데이트 되는 문서를 따라가지 못하고 지금과 같은 상황이 반복될 것 같습니다.

**Comment by devFallingstar** [comment]
의견에 동의합니다.

말씀하신대로 전체적인 효율을 고려해보았을 때, 기존에 번역된 한글 문서를 보유한 상태로 클론하는 것이 좋을 것 같네요.

**Comment by Hyuntae-91** [comment]
또 다른 의견이 있을 수 있으니 하루 내지 이틀정도 현 이슈를 열어두고, 의견을 총합하여 그 뒤에 버전을 넘어가는걸로 하는게 어떨까요?
물론, 현 시점에서 번역을 시작하는건 0.5.1버전으로 시작하는게 좋을 것 같습니다.

**Comment by devFallingstar** [comment]
네 주말동안 상황을 지켜보고 다음주 초에 버전 업데이트 진행을 하는 것이 좋겠네요 :)

**Comment by Yunbin-Chang** [comment]
브런치를 나누자는 의견에 전적으로 동의하고, 이방법을 실현시킬만한 의견을 하나 내봅니다.

[여기를 참고해주세요](https://www.diffchecker.com/cblLjeFw)

위 링크처럼 영문 버전에서 어떤 변화가 있었는지 단순 비교하여 변화된 부분만 재 번역 하는 방법이 좋을것 같습니다. 만약 처음부터 다시 번역을 시작하면 새로운 버전이 나오기 전까지 0.5.2 버전 번역을 마치지 못할것이라 생각합니다.

> 위 링크처럼 영문 버전에서의 변화를 단순비교하여 변화된 부분만 다시 번역한다면, 어느정도 번역된 0.4.2 버전을 클론하여 0.5.1 버전으로 이어나갈 수 있지 않을까 싶습니다. 위 링크를 이용하면 어느 부분에 변화가 있었는지 찾는 데 요구되는 시간이 줄어 들것이라고 생각합니다.

**Comment by Hyuntae-91** [comment]
@Yunbin-Chang 
지금 우리에게 딱 필요한 좋은 사이트네요! 향후 번역이 진행된 문서를 업데이트 하는데 요긴하게 쓰일 수 있을 것 같습니다!

**Comment by Hyuntae-91** [comment]
@devFallingstar @Yunbin-Chang 추가적인 다른 의견이 없는듯 하니, 0.4.2는 브랜치로 백업을하고, 0.5.1 문서를 가져오는 작업을 진행하면 될 것 같습니다.
