### ISSUE TITLE
이슈 태그에 대한 의견

### ISSUE THREAD

**Issue by devFallingstar** [solidity-korea/solidity-docs-kr#46]
이슈를 남길 때, 이슈 앞에 태그를 다는 것은 어떨까요?

번역에 대한 이슈면 [번역],
의견 제안에 대한 이슈면 [제안],
이런 식으로 위와 같이 태그를 붙이는 룰에 대해서 제안합니다.

자유롭게 의견 제시 해주세요 :)

**Comment by Hyuntae-91** [comment]
지금까지는 @devFallingstar 님과 제가 하나하나 붙여드렸지만, 자발적으로 참여해 주시면 감사하겠습니다!
더불어, Assignees 도 자신으로 Assign 부탁드립니다!

**Comment by Hyuntae-91** [comment]
@devFallingstar 그리고 이 내용을 템플릿에 추가하는게 어떨까요? 새로운 기여자가 오셨을때, 참고할 수 있도록 알려주면 좋을것 같습니다.
