### ISSUE TITLE
Document 페이지 업데이트

### ISSUE THREAD

**Issue by Hyuntae-91** [solidity-korea/solidity-docs-kr#54]
문서가 0.5.1버전으로 업데이트 되었습니다.

하지만 다음과 같이 문서페이지는 업데이트가 되지 않은 상황입니다.
![123](https://user-images.githubusercontent.com/43424015/50301813-2ca46c00-043d-11e9-878b-f2db63821f4b.png)

제가 저 페이지를 건드리는 방법을 몰라서 그런데 혹시 수정 가능하신분 계신가요?

**Comment by Hyuntae-91** [comment]
확인해보니 @dongsam 님이 해당 페이지 관리자 이신것 같습니다. 혹시 최신버전으로 업데이트 가능할까요? 감사합니다.

**Comment by dongsam** [comment]
안녕하세요 제가 개인적인 일로 최근 관리하고있지 못하는데 열심히 참여해주셔서 감사합니다.
현재 보기로는 https://readthedocs.org/projects/solidity-kr/builds/8306683/ 에서 빌드에 에러가 있긴하지만 마지막 커밋까지 모두 적용되어 있는것으로 보이긴 합니다. 

어느부분의 문구가 어떻게 업데이트되어야하는지 말씀해주시면 좀더 상세히 확인해서 답변드릴 수 있도록 하겠습니다.

더불어 https://readthedocs.org 가입 후 계정 명 남주시면 해당 문서 관리자에 추가해드리도록 하겠습니다 🙇‍♂️

**Comment by Hyuntae-91** [comment]
@dongsam 
본래 순서가 다음과 같아야 합니다.

![123](https://user-images.githubusercontent.com/43424015/50350499-3b018f00-04f4-11e9-9f4c-6cf9ebb5954a.png)

Resources와 LLL 이 추가되었고
Joyfully ~~~ 는 Yul로 대체되었습니다.
Keyword index도 최신 리스트에 있지만, 따로 rst 파일은 없는듯 합니다.
[공식 document URL](https://solidity.readthedocs.io/en/latest/genindex.html)

계정명은 tangyi7191 입니다. 
감사합니다.

**Comment by Hyuntae-91** [comment]
LLL.rst 파일이 빠진걸 확인했습니다. 다음 풀리퀘스트에 업데이트 될 예정입니다.

**Comment by Hyuntae-91** [comment]
![1](https://user-images.githubusercontent.com/43424015/50467101-30148780-0956-11e9-87c4-793a4f424cbc.png)

버그가 일부 픽스되었습니다. 
LLL과 Keyword Index가 보이지 않는 버그는 향후 수정할 예정입니다.

**Comment by Hyuntae-91** [comment]
해당 버그는 Unicode에러로 확인되었고, 지난 9개월간 계속해서 build fail이 돼왔던걸로 확인되었습니다.
다만, 이 버그가 문서 업데이트에는 큰 영향을 안미치는것으로 보입니다.

이 문제를 해결하기 위해 구글서치를 계속 진행하고 있습니다.

**Comment by Hyuntae-91** [comment]
Build fail 이슈를 해결하기 위해서 구글 검색을 해 본 결과
유니코드 패키지를 import하기 위해 "conf.py" 파일의 "latex_elements" 부분을 수정해야한다는 것을 확인 했습니다.
한글 유니코드에는 \usepackage{hangul}, \usepackage{hfont}, \usepackage{kotex} 세가지가 존재하는데, 마지막 패키지를 사용하였습니다.
그리고 latex_elements 부분에 해당 구문을 추가해 주었습니다.

![1](https://user-images.githubusercontent.com/43424015/50493916-2847f800-09d5-11e9-895b-315f7ee945ff.png)


그리고 빌딩된 결과는 다음과 같습니다.
![2](https://user-images.githubusercontent.com/43424015/50493921-3269f680-09d5-11e9-98fb-5ca4dcc68afe.png)

**Comment by dongsam** [comment]
감사합니다 !
