### ISSUE TITLE
Solidity 영문 docs 버전 업데이트에 따른 최신버전 pull 방안 

### ISSUE THREAD

**Issue by dongsam** [solidity-korea/solidity-docs-kr#6]
해당 Repo 를 세팅할 때 기존 타 언어에 대한 번역 사례인 
- [Spanish](https://github.com/AdrianClv/solidity-docs-es) 
- [Simplified Chinese](https://github.com/etherchina/solidity-doc-cn) 

가 선택한 방식대로 [Solidity](https://github.com/ethereum/solidity) repo 를 Fork 하는것이 아닌 docs 부분만 copy 하는 방식으로 repo 를 생성하여 번역을 진행하는 방안을 택했습니다. 

하지만 copy 할때의 버전 기준으로는 0.4.20 이였지만 그 사이 원본 영문 문서의 경우  [0.4.21](http://solidity.readthedocs.io/en/v0.4.21/) 로 업데이트 되었습니다.

이처럼 원본 영문 문서가 지속적으로 업데이트 되고있는 상황에서 추가, 수정된 내용들을 어떻게 트래킹이나 pull 할 수 있을지 고민입니다. 혹시 이 같은 상황에 대한 솔루션이나 좋은 아이디어 있으시면 댓글 부탁드립니다.

**Comment by JaeYeopHan** [comment]
solidity 본 저장소를 fork 하여 version update 시 diff에 대해서 수작업으로 추가 번역하는 것 말고는... 생각을 해봤는데 좋은 방법이 생각나지는 않네요... 뭔가 방법은 있어도 배보다 배꼽이 더 커지는(?) 그런 상황이 될 것 같습니다 ㅜㅜ

**Comment by wooqii** [comment]
업데이트 될때 마다 수작업으로 변경하는 방법이 가장 최선이 아닐까 싶습니다.

**Comment by Hyuntae-91** [comment]
#41 문서 업데이트에 대한 새로운 이슈를 발행했으니, 다음 커뮤니케이션은 해당 이슈에서 진행하는 것으로 하겠습니다. 감사합니다.
